Repository openhwgroup/cv32e40p, pull requests merged in 2023-09, with the labels that each got.

#865 Issue #862 correction.
  rtl/cv32e40p_controller.sv
Labels: Component:RTL

#861 Rvfi - Fixing gpr reporting when apu collide with instruction in EX
  bhv/cv32e40p_rvfi.sv
  bhv/cv32e40p_tb_wrapper.sv
  bhv/pipe_freeze_trace.sv
Labels: Component:Verif

#864 User Manual updates
  docs/source/corev_hw_loop.rst
  docs/source/instruction_set_extensions.rst
Labels: Component:Doc

#867 Better mstatus when FPU instruction
  bhv/cv32e40p_rvfi.sv
Labels: Component:Verif

#871 Adding physical address for memory access on rvfi trace log
  bhv/cv32e40p_rvfi.sv
  bhv/cv32e40p_rvfi_trace.sv
  bhv/cv32e40p_tb_wrapper.sv
  bhv/pipe_freeze_trace.sv
Labels: Component:Verif

#872 RVFI - fixing dcsr reporting and cv.lbu reporting issue when in debug test
  bhv/cv32e40p_rvfi.sv
Labels: Component:Verif

#874 RVFI - Adding valid bit to mem req id
  bhv/cv32e40p_rvfi.sv
  bhv/insn_trace.sv
Labels: Component:Verif
